trigger:
  branches:
    include:
      - main

pr:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

parameters:
  - name: environment_components
    type: object
    default:
      - deployment: sbox
        environment: sbox
        landing_zones: 
          - landing_zone: '00'
            Client_ID: $(SBOX_CLIENT_ID)
            Subscription_ID: $(SBOX_SUBSCRIPTION_ID)
            Client_Secret: $(SBOX_CLIENT_SECRET)
            Tenant_ID: $(TENANT_ID)
            StorageAccount: 'devops00sasbox'
            ResourceGroup: 'devops00-rg-sbox'
            KeyVaultName: 'devops00-kv-sbox'

      - deployment: stg
        environment: stg
        landing_zones: 
          - landing_zone: '00'
            Client_ID: $(STG_CLIENT_ID)
            Client_Secret: $(STG_CLIENT_SECRET)
            Subscription_ID: $(STG_SUBSCRIPTION_ID)
            Tenant_ID: $(TENANT_ID)
            StorageAccount: 'devops00sastg'
            ResourceGroup: 'devops00-rg-stg'
            KeyVaultName: 'devops00-kv-stg'

      - deployment: prod
        environment: prod
        landing_zones: 
          - landing_zone: '00'
            Client_ID: $(PROD_CLIENT_ID)
            Subscription_ID: $(PROD_SUBSCRIPTION_ID)
            Client_Secret: $(PROD_CLIENT_SECRET)
            Tenant_ID: $(TENANT_ID)
            StorageAccount: 'devops00saprod'
            ResourceGroup: 'devops00-rg-prod'
            KeyVaultName: 'devops00-kv-prod'

stages:
  - stage: Init
    displayName: 'No dependency stage'
    jobs:
      - job: BuildJob
        displayName: 'Build Job'
        steps:
          - script: echo 'Initial stage set-up'
            displayName: 'Initial stage set-up'

  - ${{ each deployment in parameters.environment_components }}:
    - ${{ if or(eq(deployment.environment, 'stg'), eq(deployment.environment, 'prod')) }}:
      - stage: Manual_Approval_${{ deployment.environment }}
        displayName: 'Manual Approval for ${{ deployment.environment }}'
        dependsOn: Init
        jobs:
          - job: waitForValidation
            displayName: Wait for Manual Validation
            pool: server
            steps:
              - task: ManualValidation@1
                timeoutInMinutes: 23160
                inputs:
                  approvers: andrew.mcdevitt@hmcts.net
                  instructions: Please validate the build configuration and resume

  - ${{ each deployment in parameters.environment_components }}:
    - ${{ each lz in deployment.landing_zones}}:
      - stage: Bootstrap_${{ deployment.environment }}_${{ lz.landing_zone }}
        displayName: 'Initialise Terraform Backend'
        ${{ if or(eq(deployment.environment, 'stg'), eq(deployment.environment, 'prod')) }}:
          dependsOn: Manual_Approval_${{ deployment.environment }}
        ${{ else }}:
          dependsOn: Init
        jobs:
        - job: BuildAndBootstrap
          displayName: 'Bootstrap TF Backend'
          pool:
            vmImage: 'ubuntu-latest'
          steps:
          - script: |
              echo "Logging in with SP..."
              az login --service-principal \
                  --username ${{ lz.Client_ID }} \
                  --password ${{ lz.Client_Secret }} \
                  --tenant ${{ lz.Tenant_ID }}

              echo "Checking subscriptions available to SP..."
              az account list --query "[].{name:name, id:id}" -o table

              # Optionally set subscription explicitly
              az account set --subscription ${{ lz.Subscription_ID }}
              echo "Account Subscription set to ${{ lz.Subscription_ID }}""

              echo "Confirm current subscription...""
              az account show --output table
              echo "Success! Logged in with SP ${{ lz.Client_ID }}"

              echo 'Create Resource Group'
              az group create \
                  --name ${{ lz.ResourceGroup }} \
                  --location "UK South"

              echo 'Create Storage Account'
              az storage account create --name ${{ lz.StorageAccount }} \
                  --resource-group ${{ lz.ResourceGroup }} \
                  --location "UK South" \
                  --sku Standard_LRS \
                  --kind StorageV2 \
                  --enable-hierarchical-namespace true

              echo "Assigning SP Blob Contributor Access"
              az role assignment create \
                --assignee "${{ lz.Client_ID }}" \
                --role "Storage Blob Data Contributor" \
                --scope "/subscriptions/${{ lz.Subscription_ID }}/resourceGroups/${{ lz.ResourceGroup }}/providers/Microsoft.Storage/storageAccounts/${{ lz.StorageAccount }}"

              echo "Retrieving Storage Account Key"
              storage_account_key=$(az storage account keys list \
                --resource-group ${{ lz.ResourceGroup }} \
                --account-name ${{ lz.StorageAccount }} \
                --query '[0].value' -o tsv)
              echo "Success! ${{ lz.StorageAccount }} storake account key is $storage_account_key"

              echo "Retrieving Blob Endpoint"
              blob_endpoint=$(az storage account show \
                --resource-group ${{ lz.ResourceGroup }} \
                --name ${{ lz.StorageAccount }} \
                --query "primaryEndpoints.blob" -o tsv)
              echo "Success! ${{ lz.StorageAccount }} blob endpoint is $blob_endpoint"

              echo "Creating tf-backend container if not exists"
              az storage container create \
                --account-name ${{ lz.StorageAccount }} \
                --name tf-backend \
                --account-key $storage_account_key \
                --blob-endpoint $blob_endpoint
              echo "Success! tf-backend container created!"
            displayName: 'Bootstrap TF backend storage (Azure CLI login with SP)'       


  #       - script: |
  #           cd $(Build.SourcesDirectory)
  #           docker compose build
  #         displayName: 'Build Docker Images'


  # - stage: Linting
  #   displayName: 'Run Linting'
  #   dependsOn: Init
  #   jobs:
  #     - job: LintPython
  #       displayName: 'Lint Python Code to PEP8 standards'
  #       steps:
  #         - task: UsePythonVersion@0
  #           displayName: 'Use Python 3.x'
  #           inputs:
  #             versionSpec: '3.x'

  #         - script: |
  #             pip install --upgrade pip
  #             pip install uv
  #             uv tool install ruff

  #             cd $(Build.SourcesDirectory)/src/backend/app

  #             uv run ruff format .
  #             uv run ruff check --fix .
  #           displayName: 'Code linting'
      
  #     # - job: SonarQubeAnalysis
  #     #   displayName: 'Run SonarScanner CLI'
  #     #   steps:
  #     #     - script: |
  #     #         export SONAR_SCANNER_VERSION=7.2.0.5079
  #     #         export SONAR_SCANNER_HOME=$HOME/.sonar/sonar-scanner-$SONAR_SCANNER_VERSION-linux-x64
  #     #         curl --create-dirs -sSLo $HOME/.sonar/sonar-scanner.zip \
  #     #           https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-$SONAR_SCANNER_VERSION-linux-x64.zip
  #     #         unzip -o $HOME/.sonar/sonar-scanner.zip -d $HOME/.sonar/
  #     #         export PATH=$SONAR_SCANNER_HOME/bin:$PATH

  #     #         sonar-scanner \
  #     #           -Dsonar.organization=ado-sonarqube \
  #     #           -Dsonar.projectKey=ado-sonarqube_ad \
  #     #           -Dsonar.login=$(SONAR_TOKEN)
  #     #       displayName: 'Install and run SonarScanner'
  #     #       env:
  #     #         SONAR_TOKEN: $(SONAR_TOKEN)
          
  # # - stage: Testing
  # #   displayName: 'Run Unit Tests'
  # #   dependsOn: Linting
  # #   jobs:
  # #     - job: RunTests
  # #       displayName: 'Unit Tests'
  # #       steps:
  # #         - task: UsePythonVersion@0
  # #           displayName: 'Use Python 3.x'
  # #           inputs:
  # #             versionSpec: '3.x'

  # #         - script: |
  # #             pip install --upgrade pip
  # #             pip install pytest
  # #             pytest $(Build.SourcesDirectory)/Python/test_maths_addition.py
  # #           displayName: 'Run pytest on maths.py' #point to new back end python
      
  # - stage: Build
  #   displayName: 'Build Docker Images'
  #   dependsOn: Linting
  #   jobs:
  #     - job: BuildAndBootstrap
  #       displayName: 'Build Docker & Bootstrap TF Backend'
  #       pool:
  #         vmImage: 'ubuntu-latest'
  #       steps:
  #         - script: |
  #             cd $(Build.SourcesDirectory)
  #             docker compose build
  #           displayName: 'Build Docker Images'
