FROM python:3.12-slim

WORKDIR /app
RUN pip install uv


# Copy dependency files
COPY pyproject.toml uv.lock ./
RUN uv sync --frozen
RUN pip install fastapi uvicorn[standard] sqlalchemy psycopg2-binary python-dotenv requests python-multipart
RUN apt-get update && apt-get install -y postgresql-client

# Copy backend code
COPY src/backend /app

EXPOSE 8000

CMD ["python", "-m", "uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--workers", "2"]

