trigger:
  branches:
    include:
      - main

pr:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

parameters:
  - name: environment_components
    type: object
    default:
      - deployment: sbox
        environment: sbox
        landing_zones: 
          - landing_zone: '00'
            Client_ID: $(SBOX_CLIENT_ID)
            Subscription_ID: $(SBOX_SUBSCRIPTION_ID)
            Client_Secret: $(SBOX_CLIENT_SECRET)
            Tenant_ID: $(TENANT_ID)
            StorageAccount: 'devops00sasbox'
            ResourceGroup: 'devops00-rg-sbox'
            KeyVaultName: 'devops00-kv-sbox'

      - deployment: stg
        environment: stg
        landing_zones: 
          - landing_zone: '00'
            Client_ID: $(STG_CLIENT_ID)
            Client_Secret: $(STG_CLIENT_SECRET)
            Subscription_ID: $(STG_SUBSCRIPTION_ID)
            Tenant_ID: $(TENANT_ID)
            StorageAccount: 'devops00sastg'
            ResourceGroup: 'devops00-rg-stg'
            KeyVaultName: 'devops00-kv-stg'

      - deployment: prod
        environment: prod
        landing_zones: 
          - landing_zone: '00'
            Client_ID: $(PROD_CLIENT_ID)
            Subscription_ID: $(PROD_SUBSCRIPTION_ID)
            Client_Secret: $(PROD_CLIENT_SECRET)
            Tenant_ID: $(TENANT_ID)
            StorageAccount: 'devops00saprod'
            ResourceGroup: 'devops00-rg-prod'
            KeyVaultName: 'devops00-kv-prod'

stages:
  - stage: Init
    displayName: 'No dependency stage'
    jobs:
      - job: BuildJob
        displayName: 'Build Job'
        steps:
          - script: echo 'Initial stage set-up'
            displayName: 'Initial stage set-up'

  - ${{ each deployment in parameters.environment_components }}:
    - ${{ if or(eq(deployment.environment, 'stg'), eq(deployment.environment, 'prod')) }}:
      - stage: Manual_Approval_${{ deployment.environment }}
        displayName: 'Manual Approval for ${{ deployment.environment }}'
        dependsOn: Init
        jobs:
          - job: waitForValidation
            displayName: Wait for Manual Validation
            pool: server
            steps:
              - task: ManualValidation@1
                timeoutInMinutes: 23160
                inputs:
                  approvers: andrew.mcdevitt@hmcts.net
                  instructions: Please validate the build configuration and resume

  - ${{ each deployment in parameters.environment_components }}:
    - ${{ each lz in deployment.landing_zones}}:
      - stage: Bootstrap_${{ deployment.environment }}_${{ lz.landing_zone }}
        displayName: 'Initialise Terraform Backend'
        ${{ if or(eq(deployment.environment, 'stg'), eq(deployment.environment, 'prod')) }}:
          dependsOn: Manual_Approval_${{ deployment.environment }}
        ${{ else }}:
          dependsOn: Init
        jobs:
        - job: BuildAndBootstrap
          displayName: 'Bootstrap TF Backend'
          pool:
            vmImage: 'ubuntu-latest'
          steps:
          - script: |
              echo "Logging in with SP..."
              az login --service-principal \
                  --username ${{ lz.Client_ID }} \
                  --password ${{ lz.Client_Secret }} \
                  --tenant ${{ lz.Tenant_ID }}

              echo "Checking subscriptions available to SP..."
              az account list --query "[].{name:name, id:id}" -o table

              # Optionally set subscription explicitly
              az account set --subscription ${{ lz.Subscription_ID }}
              echo "Account Subscription set to ${{ lz.Subscription_ID }}"

              echo "Confirm current subscription..."
              az account show --output table
              echo "Success! Logged in with SP ${{ lz.Client_ID }}"

              echo 'Create Resource Group'
              az group create \
                  --name ${{ lz.ResourceGroup }} \
                  --location "UK South"

              echo 'Create Storage Account'
              az storage account create --name ${{ lz.StorageAccount }} \
                  --resource-group ${{ lz.ResourceGroup }} \
                  --location "UK South" \
                  --sku Standard_LRS \
                  --kind StorageV2 \
                  --enable-hierarchical-namespace true

              echo "Assigning SP Blob Contributor Access"
              az role assignment create \
                --assignee "${{ lz.Client_ID }}" \
                --role "Storage Blob Data Contributor" \
                --scope "/subscriptions/${{ lz.Subscription_ID }}/resourceGroups/${{ lz.ResourceGroup }}/providers/Microsoft.Storage/storageAccounts/${{ lz.StorageAccount }}"

              echo "Retrieving Storage Account Key"
              storage_account_key=$(az storage account keys list \
                --resource-group ${{ lz.ResourceGroup }} \
                --account-name ${{ lz.StorageAccount }} \
                --query '[0].value' -o tsv)
              echo "Success! ${{ lz.StorageAccount }} storake account key is $storage_account_key"

              echo "Retrieving Blob Endpoint"
              blob_endpoint=$(az storage account show \
                --resource-group ${{ lz.ResourceGroup }} \
                --name ${{ lz.StorageAccount }} \
                --query "primaryEndpoints.blob" -o tsv)
              echo "Success! ${{ lz.StorageAccount }} blob endpoint is $blob_endpoint"

              echo "Creating tf-backend container if not exists"
              az storage container create \
                --account-name ${{ lz.StorageAccount }} \
                --name tf-backend \
                --account-key $storage_account_key \
                --blob-endpoint $blob_endpoint
              echo "Success! tf-backend container created!"
            displayName: 'Bootstrap TF backend storage (Azure CLI login with SP)' 

          - task: TerraformInstaller@0
            inputs:
              terraformVersion: 'latest'
            displayName: 'Install Terraform using TerraformInstaller@0'

          - script: |   
              cd $(Build.SourcesDirectory)/terraform           
              terraform --version
              terraform init -input=false \
                -backend-config="resource_group_name=${{ lz.ResourceGroup }}" \
                -backend-config="storage_account_name=${{ lz.StorageAccount }}" \
                -backend-config="container_name=tf-backend" \
                -backend-config="key=${{ lz.landing_zone }}/terraform.tfstate"
            displayName: 'Terraform Init & initialise backend'
          
          - script: |
              curl -s https://raw.githubusercontent.com/terraform-linters/tflint/master/install_linux.sh | bash
              tflint --version
            displayName: 'Install TFLint'

          - script: |
              cd $(Build.SourcesDirectory)/terraform
              terraform validate
            displayName: 'Terraform Validate'

          - script: |
              cd $(Build.SourcesDirectory)/terraform
              tflint --init
              tflint
            displayName: 'Terraform Lint'

          - script: |
              cd $(Build.SourcesDirectory)/terraform
              terraform plan \
                -out=tfplan \
                -var env=${{ deployment.environment }} \
                -var="subscription_id=${{ lz.Subscription_ID }}" \
                -var="client_id=${{ lz.Client_ID }}" \
                -lock=false     
              terraform show -no-color tfplan > tfplan.txt
            displayName: 'Terraform Plan'
          
          - publish: "$(Build.SourcesDirectory)/terraform/tfplan"
            artifact: "tfplan_${{ deployment.environment }}_${{ lz.landing_zone }}"
            displayName: "Publish Terraform Plan Artifact"
